// Kota & Kabupaten per Provinsi Indonesia
export const CITIES_ID = {
    "Aceh": [
        "Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Subulussalam",
        "Kab. Aceh Barat", "Kab. Aceh Barat Daya", "Kab. Aceh Besar", "Kab. Aceh Jaya",
        "Kab. Aceh Selatan", "Kab. Aceh Singkil", "Kab. Aceh Tamiang", "Kab. Aceh Tengah",
        "Kab. Aceh Tenggara", "Kab. Aceh Timur", "Kab. Aceh Utara", "Kab. Bener Meriah",
        "Kab. Bireuen", "Kab. Gayo Lues", "Kab. Nagan Raya", "Kab. Pidie", "Kab. Pidie Jaya",
        "Kab. Simeulue",
    ],
    "Bali": [
        "Denpasar",
        "Kab. Badung", "Kab. Bangli", "Kab. Buleleng", "Kab. Gianyar",
        "Kab. Jembrana", "Kab. Karangasem", "Kab. Klungkung", "Kab. Tabanan",
    ],
    "Bangka Belitung": [
        "Pangkal Pinang",
        "Kab. Bangka", "Kab. Bangka Barat", "Kab. Bangka Selatan", "Kab. Bangka Tengah",
        "Kab. Belitung", "Kab. Belitung Timur",
    ],
    "Banten": [
        "Cilegon", "Serang", "Tangerang", "Tangerang Selatan",
        "Kab. Lebak", "Kab. Pandeglang", "Kab. Serang", "Kab. Tangerang",
    ],
    "Bengkulu": [
        "Bengkulu",
        "Kab. Bengkulu Selatan", "Kab. Bengkulu Tengah", "Kab. Bengkulu Utara",
        "Kab. Kaur", "Kab. Kepahiang", "Kab. Lebong", "Kab. Muko Muko",
        "Kab. Rejang Lebong", "Kab. Seluma",
    ],
    "DI Yogyakarta": [
        "Yogyakarta",
        "Kab. Bantul", "Kab. Gunungkidul", "Kab. Kulon Progo", "Kab. Sleman",
    ],
    "DKI Jakarta": [
        "Jakarta Barat", "Jakarta Pusat", "Jakarta Selatan",
        "Jakarta Timur", "Jakarta Utara", "Kep. Seribu",
    ],
    "Gorontalo": [
        "Gorontalo",
        "Kab. Boalemo", "Kab. Bone Bolango", "Kab. Gorontalo", "Kab. Gorontalo Utara",
        "Kab. Pohuwato",
    ],
    "Jambi": [
        "Jambi", "Sungai Penuh",
        "Kab. Batanghari", "Kab. Bungo", "Kab. Kerinci", "Kab. Merangin",
        "Kab. Muaro Jambi", "Kab. Sarolangun", "Kab. Tanjung Jabung Barat",
        "Kab. Tanjung Jabung Timur", "Kab. Tebo",
    ],
    "Jawa Barat": [
        "Bandung", "Bekasi", "Bogor", "Cimahi", "Cirebon", "Depok",
        "Sukabumi", "Tasikmalaya",
        "Kab. Bandung", "Kab. Bandung Barat", "Kab. Bekasi", "Kab. Bogor",
        "Kab. Ciamis", "Kab. Cianjur", "Kab. Cirebon", "Kab. Garut",
        "Kab. Indramayu", "Kab. Karawang", "Kab. Kuningan", "Kab. Majalengka",
        "Kab. Pangandaran", "Kab. Purwakarta", "Kab. Subang", "Kab. Sukabumi",
        "Kab. Sumedang", "Kab. Tasikmalaya",
    ],
    "Jawa Tengah": [
        "Magelang", "Pekalongan", "Salatiga", "Semarang", "Surakarta", "Tegal",
        "Kab. Banjarnegara", "Kab. Banyumas", "Kab. Batang", "Kab. Blora",
        "Kab. Boyolali", "Kab. Brebes", "Kab. Cilacap", "Kab. Demak",
        "Kab. Grobogan", "Kab. Jepara", "Kab. Karanganyar", "Kab. Kebumen",
        "Kab. Kendal", "Kab. Klaten", "Kab. Kudus", "Kab. Magelang",
        "Kab. Pati", "Kab. Pekalongan", "Kab. Pemalang", "Kab. Purbalingga",
        "Kab. Purworejo", "Kab. Rembang", "Kab. Semarang", "Kab. Sragen",
        "Kab. Sukoharjo", "Kab. Tegal", "Kab. Temanggung", "Kab. Wonogiri",
        "Kab. Wonosobo",
    ],
    "Jawa Timur": [
        "Batu", "Blitar", "Kediri", "Madiun", "Malang", "Mojokerto",
        "Pasuruan", "Probolinggo", "Surabaya",
        "Kab. Bangkalan", "Kab. Banyuwangi", "Kab. Blitar", "Kab. Bojonegoro",
        "Kab. Bondowoso", "Kab. Gresik", "Kab. Jember", "Kab. Jombang",
        "Kab. Kediri", "Kab. Lamongan", "Kab. Lumajang", "Kab. Madiun",
        "Kab. Magetan", "Kab. Malang", "Kab. Mojokerto", "Kab. Nganjuk",
        "Kab. Ngawi", "Kab. Pacitan", "Kab. Pamekasan", "Kab. Pasuruan",
        "Kab. Ponorogo", "Kab. Probolinggo", "Kab. Sampang", "Kab. Sidoarjo",
        "Kab. Situbondo", "Kab. Sumenep", "Kab. Trenggalek", "Kab. Tuban",
        "Kab. Tulungagung",
    ],
    "Kalimantan Barat": [
        "Pontianak", "Singkawang",
        "Kab. Bengkayang", "Kab. Kapuas Hulu", "Kab. Kayong Utara", "Kab. Ketapang",
        "Kab. Kubu Raya", "Kab. Landak", "Kab. Melawi", "Kab. Mempawah",
        "Kab. Sambas", "Kab. Sanggau", "Kab. Sekadau", "Kab. Sintang",
    ],
    "Kalimantan Selatan": [
        "Banjarbaru", "Banjarmasin",
        "Kab. Balangan", "Kab. Banjar", "Kab. Barito Kuala", "Kab. Hulu Sungai Selatan",
        "Kab. Hulu Sungai Tengah", "Kab. Hulu Sungai Utara", "Kab. Kotabaru",
        "Kab. Tabalong", "Kab. Tanah Bumbu", "Kab. Tanah Laut", "Kab. Tapin",
    ],
    "Kalimantan Tengah": [
        "Palangka Raya",
        "Kab. Barito Selatan", "Kab. Barito Timur", "Kab. Barito Utara",
        "Kab. Gunung Mas", "Kab. Kapuas", "Kab. Katingan", "Kab. Kotawaringin Barat",
        "Kab. Kotawaringin Timur", "Kab. Lamandau", "Kab. Murung Raya",
        "Kab. Pulang Pisau", "Kab. Seruyan", "Kab. Sukamara",
    ],
    "Kalimantan Timur": [
        "Balikpapan", "Bontang", "Samarinda",
        "Kab. Berau", "Kab. Kutai Barat", "Kab. Kutai Kartanegara", "Kab. Kutai Timur",
        "Kab. Mahakam Ulu", "Kab. Paser", "Kab. Penajam Paser Utara",
    ],
    "Kalimantan Utara": [
        "Tarakan",
        "Kab. Bulungan", "Kab. Malinau", "Kab. Nunukan", "Kab. Tana Tidung",
    ],
    "Kepulauan Riau": [
        "Batam", "Tanjung Pinang",
        "Kab. Anambas", "Kab. Bintan", "Kab. Karimun", "Kab. Lingga",
        "Kab. Natuna",
    ],
    "Lampung": [
        "Bandar Lampung", "Metro",
        "Kab. Lampung Barat", "Kab. Lampung Selatan", "Kab. Lampung Tengah",
        "Kab. Lampung Timur", "Kab. Lampung Utara", "Kab. Mesuji",
        "Kab. Pesawaran", "Kab. Pesisir Barat", "Kab. Pringsewu",
        "Kab. Tanggamus", "Kab. Tulang Bawang", "Kab. Tulang Bawang Barat",
        "Kab. Way Kanan",
    ],
    "Maluku": [
        "Ambon", "Tual",
        "Kab. Buru", "Kab. Buru Selatan", "Kab. Kepulauan Aru", "Kab. Maluku Barat Daya",
        "Kab. Maluku Tengah", "Kab. Maluku Tenggara", "Kab. Maluku Tenggara Barat",
        "Kab. Seram Bagian Barat", "Kab. Seram Bagian Timur",
    ],
    "Maluku Utara": [
        "Ternate", "Tidore Kepulauan",
        "Kab. Halmahera Barat", "Kab. Halmahera Selatan", "Kab. Halmahera Tengah",
        "Kab. Halmahera Timur", "Kab. Halmahera Utara", "Kab. Kepulauan Sula",
        "Kab. Pulau Morotai", "Kab. Pulau Taliabu",
    ],
    "Nusa Tenggara Barat": [
        "Bima", "Mataram",
        "Kab. Bima", "Kab. Dompu", "Kab. Lombok Barat", "Kab. Lombok Tengah",
        "Kab. Lombok Timur", "Kab. Lombok Utara", "Kab. Sumbawa", "Kab. Sumbawa Barat",
    ],
    "Nusa Tenggara Timur": [
        "Kupang",
        "Kab. Alor", "Kab. Belu", "Kab. Ende", "Kab. Flores Timur", "Kab. Kupang",
        "Kab. Lembata", "Kab. Malaka", "Kab. Manggarai", "Kab. Manggarai Barat",
        "Kab. Manggarai Timur", "Kab. Nagekeo", "Kab. Ngada", "Kab. Rote Ndao",
        "Kab. Sabu Raijua", "Kab. Sikka", "Kab. Sumba Barat", "Kab. Sumba Barat Daya",
        "Kab. Sumba Tengah", "Kab. Sumba Timur", "Kab. Timor Tengah Selatan",
        "Kab. Timor Tengah Utara",
    ],
    "Papua": [
        "Jayapura",
        "Kab. Jayapura", "Kab. Jayawijaya", "Kab. Keerom", "Kab. Mamberamo Raya",
        "Kab. Sarmi", "Kab. Supiori", "Kab. Waropen", "Kab. Yalimo",
    ],
    "Papua Barat": [
        "Sorong",
        "Kab. Fakfak", "Kab. Kaimana", "Kab. Manokwari", "Kab. Manokwari Selatan",
        "Kab. Pegunungan Arfak", "Kab. Raja Ampat", "Kab. Sorong",
        "Kab. Sorong Selatan", "Kab. Teluk Bintuni", "Kab. Teluk Wondama",
    ],
    "Papua Barat Daya": [
        "Sorong",
        "Kab. Maybrat", "Kab. Sorong", "Kab. Sorong Selatan",
        "Kab. Tambrauw",
    ],
    "Papua Pegunungan": [
        "Kab. Jayawijaya", "Kab. Lanny Jaya", "Kab. Mamberamo Tengah",
        "Kab. Nduga", "Kab. Pegunungan Bintang", "Kab. Puncak",
        "Kab. Puncak Jaya", "Kab. Tolikara", "Kab. Yahukimo", "Kab. Yalimo",
    ],
    "Papua Selatan": [
        "Kab. Asmat", "Kab. Boven Digoel", "Kab. Mappi", "Kab. Merauke",
    ],
    "Papua Tengah": [
        "Kab. Deiyai", "Kab. Dogiyai", "Kab. Intan Jaya", "Kab. Mimika",
        "Kab. Nabire", "Kab. Paniai", "Kab. Puncak",
    ],
    "Riau": [
        "Dumai", "Pekanbaru",
        "Kab. Bengkalis", "Kab. Indragiri Hilir", "Kab. Indragiri Hulu",
        "Kab. Kampar", "Kab. Kepulauan Meranti", "Kab. Kuantan Singingi",
        "Kab. Pelalawan", "Kab. Rokan Hilir", "Kab. Rokan Hulu", "Kab. Siak",
    ],
    "Sulawesi Barat": [
        "Kab. Majene", "Kab. Mamasa", "Kab. Mamuju", "Kab. Mamuju Tengah",
        "Kab. Pasangkayu", "Kab. Polewali Mandar",
    ],
    "Sulawesi Selatan": [
        "Makassar", "Palopo", "Parepare",
        "Kab. Bantaeng", "Kab. Barru", "Kab. Bone", "Kab. Bulukumba",
        "Kab. Enrekang", "Kab. Gowa", "Kab. Jeneponto", "Kab. Kepulauan Selayar",
        "Kab. Luwu", "Kab. Luwu Timur", "Kab. Luwu Utara", "Kab. Maros",
        "Kab. Pangkajene dan Kepulauan", "Kab. Pinrang", "Kab. Sidenreng Rappang",
        "Kab. Sinjai", "Kab. Soppeng", "Kab. Takalar", "Kab. Tana Toraja",
        "Kab. Toraja Utara", "Kab. Wajo",
    ],
    "Sulawesi Tengah": [
        "Palu",
        "Kab. Banggai", "Kab. Banggai Kepulauan", "Kab. Banggai Laut",
        "Kab. Buol", "Kab. Donggala", "Kab. Morowali", "Kab. Morowali Utara",
        "Kab. Parigi Moutong", "Kab. Poso", "Kab. Sigi", "Kab. Tojo Una Una",
        "Kab. Tolitoli",
    ],
    "Sulawesi Tenggara": [
        "Bau-Bau", "Kendari",
        "Kab. Bombana", "Kab. Buton", "Kab. Buton Selatan", "Kab. Buton Tengah",
        "Kab. Buton Utara", "Kab. Kolaka", "Kab. Kolaka Timur", "Kab. Kolaka Utara",
        "Kab. Konawe", "Kab. Konawe Kepulauan", "Kab. Konawe Selatan",
        "Kab. Konawe Utara", "Kab. Muna", "Kab. Muna Barat", "Kab. Wakatobi",
    ],
    "Sulawesi Utara": [
        "Bitung", "Kotamobagu", "Manado", "Tomohon",
        "Kab. Bolaang Mongondow", "Kab. Bolaang Mongondow Selatan",
        "Kab. Bolaang Mongondow Timur", "Kab. Bolaang Mongondow Utara",
        "Kab. Kepulauan Sangihe", "Kab. Kepulauan Siau Tagulandang Biaro",
        "Kab. Kepulauan Talaud", "Kab. Minahasa", "Kab. Minahasa Selatan",
        "Kab. Minahasa Tenggara", "Kab. Minahasa Utara",
    ],
    "Sumatera Barat": [
        "Bukittinggi", "Padang", "Padang Panjang", "Pariaman", "Payakumbuh",
        "Sawahlunto", "Solok",
        "Kab. Agam", "Kab. Dharmasraya", "Kab. Kepulauan Mentawai",
        "Kab. Lima Puluh Kota", "Kab. Padang Pariaman", "Kab. Pasaman",
        "Kab. Pasaman Barat", "Kab. Pesisir Selatan", "Kab. Sijunjung",
        "Kab. Solok", "Kab. Solok Selatan", "Kab. Tanah Datar",
    ],
    "Sumatera Selatan": [
        "Lubuk Linggau", "Pagar Alam", "Palembang", "Prabumulih",
        "Kab. Banyuasin", "Kab. Empat Lawang", "Kab. Lahat", "Kab. Muara Enim",
        "Kab. Musi Banyuasin", "Kab. Musi Rawas", "Kab. Musi Rawas Utara",
        "Kab. Ogan Ilir", "Kab. Ogan Komering Ilir", "Kab. Ogan Komering Ulu",
        "Kab. Ogan Komering Ulu Selatan", "Kab. Ogan Komering Ulu Timur",
        "Kab. Penukal Abab Lematang Ilir",
    ],
    "Sumatera Utara": [
        "Binjai", "Gunungsitoli", "Medan", "Padang Sidimpuan", "Pematang Siantar",
        "Sibolga", "Tanjung Balai", "Tebing Tinggi",
        "Kab. Asahan", "Kab. Batu Bara", "Kab. Dairi", "Kab. Deli Serdang",
        "Kab. Humbang Hasundutan", "Kab. Karo", "Kab. Labuhanbatu",
        "Kab. Labuhanbatu Selatan", "Kab. Labuhanbatu Utara", "Kab. Langkat",
        "Kab. Mandailing Natal", "Kab. Nias", "Kab. Nias Barat", "Kab. Nias Selatan",
        "Kab. Nias Utara", "Kab. Padang Lawas", "Kab. Padang Lawas Utara",
        "Kab. Pakpak Bharat", "Kab. Samosir", "Kab. Serdang Bedagai",
        "Kab. Simalungun", "Kab. Tapanuli Selatan", "Kab. Tapanuli Tengah",
        "Kab. Tapanuli Utara", "Kab. Toba",
    ],
};